name: Deploy from Private Repo

on:
  repository_dispatch:
    types: [trigger-from-private]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          echo "BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
          echo "DEPLOY_BACKEND=${{ github.event.client_payload.deploy_backend }}" >> $GITHUB_ENV
          echo "DEPLOY_FRONTEND=${{ github.event.client_payload.deploy_frontend }}" >> $GITHUB_ENV
          echo "FRONTEND_TYPE=${{ github.event.client_payload.frontend_type }}" >> $GITHUB_ENV
          echo "IMAGE_DESC=${{ github.event.client_payload.image_description }}" >> $GITHUB_ENV

      - name: Checkout Code from Private Repo
        uses: actions/checkout@v4
        with:
          repository: tsp1423/mdm-studio
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.TOKEN_PULL_FROM_PRIVATE_REPO }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: datamanagement-coip

      - name: Set Docker Image Name and Tag
        run: |
          IMAGE_NAME=$(echo "${{ env.BRANCH }}" | tr '/' '-')
          TAG=$(date +%Y%m%d-%H%M%S)
          DESC="${{ env.IMAGE_DESC }}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "DESC=$DESC" >> $GITHUB_ENV

      - name: Deploy Backend (Test Mode - Echo Changed Functions)
        if: env.DEPLOY_BACKEND == 'true'
        run: |
          echo "Detecting changes in Backend/UI_endpoints for ${{ env.BRANCH }}"
      
          # Ensure full Git history is available
          git fetch --unshallow || true
      
          # Get list of changed files in the latest commit
          git diff --name-only HEAD~1 HEAD > changed_files.txt
      
          echo "Changed files:"
          cat changed_files.txt

          echo "Checking for changes in Cloud Function folders:"
          find Backend/UI_endpoints -mindepth 1 -maxdepth 1 -type d | while read -r fn_dir; do
            fn_name=$(basename "$fn_dir")
            if grep -q "^$fn_dir/" changed_files.txt; then
              echo "Changed function detected: $fn_name"
            else
              echo "No changes in: $fn_name"
            fi
          done

      - name: Deploy Frontend (Non-Docker)
        if: env.DEPLOY_FRONTEND == 'true' && env.FRONTEND_TYPE == 'non-docker'
        run: |
          echo "Deploying Non-Docker Frontend for ${{ env.BRANCH }}"
          # Add non-docker frontend deployment commands here

      - name: Deploy Frontend (Docker)
        if: env.DEPLOY_FRONTEND == 'true' && env.FRONTEND_TYPE == 'docker'
        run: |
          echo "Deploying Docker frontend for ${{ env.BRANCH }}"
          gcloud builds submit frontend/ \
            --config=frontend/cloudbuild.yaml \
            --substitutions=_IMAGE=${{ env.IMAGE_NAME }},_TAG=${{ env.TAG }},_REPO=mdmstudio-ui,_REGION=us-central1,_DESC="${{ env.DESC }}"
